In [1]:
import pandas as pd

In [8]:
df = pd.read_csv('Datasets/daraz_dataset.csv')

In [11]:
df.loc[df["TotalAmount"] > 30000]

,OrderID,OrderDate,CustomerName,Age,Gender,District,Category,Product,Quantity,UnitPrice,DiscountPercent,TotalAmount,PaymentMethod,Rating,OrderStatus
0,DZ100001,2026-03-04,Anita Basnet,24,Male,Nepalgunj,Sports,Football,1,48898,10,44008.2,IME Pay,1,Delivered
1,DZ100002,2026-01-07,Pooja Basnet,52,Female,Pokhara,Electronics,Bluetooth Speaker,2,33418,20,53468.8,IME Pay,5,Cancelled
2,DZ100003,2026-03-29,Rohit Basnet,31,Female,Lalitpur,Books,Python Basics,2,46053,15,78290.1,eSewa,4,Delivered
3,DZ100004,2026-04-28,Pooja Sharma,42,Male,Chitwan,Home,Chair,5,17635,0,88175.0,COD,5,Cancelled
5,DZ100006,2026-06-29,Ram Shrestha,28,Male,Bhaktapur,Fashion,Hoodie,3,14030,10,37881.0,IME Pay,4,Cancelled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
490,DZ100491,2026-04-27,Binita Karki,29,Female,Chitwan,Fashion,T-Shirt,2,42390,15,72063.0,IME Pay,5,Returned
494,DZ100495,2026-05-01,Roshan Thapa,39,Female,Itahari,Books,Python Basics,4,30055,20,96176.0,COD,3,Shipped
495,DZ100496,2026-03-08,Sita Thapa,48,Male,Nepalgunj,Electronics,Smart Watch,3,47942,20,115060.8,eSewa,3,Processing
497,DZ100498,2026-06-04,Nabin Shrestha,27,Female,Itahari,Books,Data Science 101,1,48890,0,48890.0,Khalti,3,Shipped
499,DZ100500,2026-01-14,Rohit Adhikari,25,Male,Bhaktapur,Sports,Yoga Mat,2,38163,10,68693.4,IME Pay,4,Returned

In [23]:
df.loc[(df["Category"] == "Electronics") & (df["Rating"] == 5)]

,OrderID,OrderDate,CustomerName,Age,Gender,District,Category,Product,Quantity,UnitPrice,DiscountPercent,TotalAmount,PaymentMethod,Rating,OrderStatus
1,DZ100002,2026-01-07,Pooja Basnet,52,Female,Pokhara,Electronics,Bluetooth Speaker,2,33418,20,53468.80,IME Pay,5,Cancelled
57,DZ100058,2026-06-26,Nabin Basnet,31,Female,Biratnagar,Electronics,Bluetooth Speaker,3,8135,20,19524.00,Card,5,Processing
97,DZ100098,2026-02-02,Rohit Shrestha,55,Female,Dharan,Electronics,Power Bank,5,10021,0,50105.00,Card,5,Cancelled
180,DZ100181,2026-02-02,Anita Adhikari,18,Male,Biratnagar,Electronics,Bluetooth Speaker,5,26059,20,104236.00,IME Pay,5,Returned
205,DZ100206,2026-05-23,Ramesh Karki,24,Male,Lalitpur,Electronics,Bluetooth Speaker,4,29715,20,95088.00,COD,5,Delivered
271,DZ100272,2026-01-29,Ramesh Adhikari,41,Male,Itahari,Electronics,Bluetooth Speaker,5,46482,5,220789.50,IME Pay,5,Delivered
280,DZ100281,2026-02-09,Sita Rai,18,Female,Lalitpur,Electronics,USB Cable,5,36322,15,154368.50,COD,5,Returned
324,DZ100325,2026-05-08,Aarav Sharma,43,Female,Kathmandu,Electronics,USB Cable,4,21013,0,84052.00,Card,5,Delivered
329,DZ100330,2026-05-10,Gita Karki,18,Male,Chitwan,Electronics,USB Cable,4,43452,20,139046.40,IME Pay,5,Returned
355,DZ100356,2026-02-05,Pooja Basnet,34,Male,Lalitpur,Electronics,Bluetooth Speaker,5,5672,10,25524.00,eSewa,5,Delivered
377,DZ100378,2026-02-21,Ramesh Rai,30,Male,Nepalgunj,Electronics,Bluetooth Speaker,4,29068,0,116272.00,Card,5,Shipped
387,DZ100388,2026-01-09,Ramesh Rai,43,Male,Butwal,Electronics,Smart Watch,4,31647,20,101270.40,eSewa,5,Returned
395,DZ100396,2026-06-11,Gita Adhikari,28,Female,Dharan,Electronics,USB Cable,5,19077,15,81077.25,Card,5,Returned
484,DZ100485,2026-04-08,Bikash Karki,21,Male,Pokhara,Electronics,Smart Watch,1,45225,20,36180.00,Khalti,5,Delivered

In [27]:
df.sort_values("TotalAmount", ascending= False)
df["TotalAmount"]

0       44008.20
1       53468.80
2       78290.10
3       88175.00
4        3137.85
         ...
495    115060.80
496     21686.60
497     48890.00
498     11106.00
499     68693.40
Name: TotalAmount, Length: 500, dtype: float64